version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rw_data_portal
    container_name: data_respira_works
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_URI=$MONGO_URI
    ports:
      - "80:8080"
    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules
