version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rw_data_portal
    container_name: data_respira_works
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "80:8080"
    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules
