version: 2.1

jobs:
  common-precommit-checks:
    docker:
      - image: cimg/python:3.10.4
    environment:
      GIT_LFS_SKIP_SMUDGE: 1
    steps:
      - checkout
      - run:
          name: Install pre-commit
          command: |
            pip install pre-commit
      - run:
          name: Run pre-commit hooks
          command: |
            merge_base=$(git merge-base -a HEAD origin/master)
            changed_files=$(git diff --name-only $merge_base...HEAD)
            echo "Changed files since branched from origin/master: " $changed_files
            git reset --soft $merge_base
            pre-commit run --show-diff-on-failure --files $changed_files

workflows:
  commit:
    jobs:
      - common-precommit-checks
